/*
 * Copyright (c) 2025 GP Orcullo
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_ADC_ADC_SAM0_H_
#define ZEPHYR_DRIVERS_ADC_ADC_SAM0_H_

/* GCLK registers */

#define CLKCTRL_OFFSET 0x02
#define PCHCTRL_OFFSET 0x80

#define CLKCTRL_ID(n)  FIELD_PREP(GENMASK(5, 0), n)
#define CLKCTRL_GEN(n) FIELD_PREP(GENMASK(11, 8), n)
#define CLKCTRL_CLKEN  BIT(14)

#define PCHCTRL_GEN(n) FIELD_PREP(GENMASK(3, 0), n)
#define PCHCTRL_CHEN   BIT(6)

/* ADC Registers */

#define CTRLA_OFFSET 0x00

#define REFCTRL_REFSEL_MASK GENMASK(3, 0)
#define REFCTRL_REFSEL(n)   FIELD_PREP(REFCTRL_REFSEL_MASK, n)

#define REFCTRL_REFSEL_INTREF REFCTRL_REFSEL(0)

#define INPUTCTRL_MUXPOS_MASK GENMASK(4, 0)
#define INPUTCTRL_MUXPOS(n)   FIELD_PREP(INPUTCTRL_MUXPOS_MASK, n)

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define REFCTRL_OFFSET   0x01
#define AVGCTRL_OFFSET   0x02
#define SAMPCTRL_OFFSET  0x03
#define CTRLB_OFFSET     0x04
#define SWTRIG_OFFSET    0x0C
#define INPUTCTRL_OFFSET 0x10
#define INTENCLR_OFFSET  0x16
#define INTENSET_OFFSET  0x17
#define INTFLAG_OFFSET   0x18
#define STATUS_OFFSET    0x19
#define RESULT_OFFSET    0x1A
#define CALIB_OFFSET     0x28

#define DIFFMODE_OFFSET  CTRLB_OFFSET
#define RESSEL_OFFSET    CTRLB_OFFSET
#define PRESCALER_OFFSET CTRLB_OFFSET

#define DIFFMODE_MASK BIT(0)

#define PRESCALER_MASK GENMASK(10, 8)

#define REFCTRL_REFSEL_VDD_1_2 REFCTRL_REFSEL(2)
#define REFCTRL_REFSEL_AREFA   REFCTRL_REFSEL(3)
#define REFCTRL_REFSEL_AREFB   REFCTRL_REFSEL(4)

#define INPUTCTRL_MUXPOS_TEMP    INPUTCTRL_MUXPOS(0x18)
#define INPUTCTRL_MUXPOS_BANDGAP INPUTCTRL_MUXPOS(0x19)

#define INTFLAG_MASK  0x0F
#define INTENCLR_MASK 0x0F

#define STATUS_SYNCBUSY BIT(7)

#elif defined(CONFIG_SOC_SERIES_SAMD51) || defined(CONFIG_SOC_SERIES_SAME51) ||                    \
	defined(CONFIG_SOC_SERIES_SAME53) || defined(CONFIG_SOC_SERIES_SAME54)

#define INPUTCTRL_OFFSET 0x04
#define CTRLB_OFFSET     0x06
#define REFCTRL_OFFSET   0x08
#define AVGCTRL_OFFSET   0x0A
#define SAMPCTRL_OFFSET  0x0B
#define SWTRIG_OFFSET    0x14
#define INTENCLR_OFFSET  0x2C
#define INTENSET_OFFSET  0x2D
#define INTFLAG_OFFSET   0x2E
#define STATUS_OFFSET    0x2F
#define SYNCBUSY_OFFSET  0x30
#define RESULT_OFFSET    0x40
#define CALIB_OFFSET     0x48

#define DIFFMODE_OFFSET  INPUTCTRL_OFFSET
#define RESSEL_OFFSET    CTRLB_OFFSET
#define PRESCALER_OFFSET CTRLA_OFFSET

#define DIFFMODE_MASK BIT(7)

#define PRESCALER_MASK GENMASK(10, 8)

#define REFCTRL_REFSEL_VDD_1_2 REFCTRL_REFSEL(2)
#define REFCTRL_REFSEL_VDD_1   REFCTRL_REFSEL(3)
#define REFCTRL_REFSEL_AREFA   REFCTRL_REFSEL(4)
#define REFCTRL_REFSEL_AREFB   REFCTRL_REFSEL(5)

#define INPUTCTRL_MUXPOS_BANDGAP INPUTCTRL_MUXPOS(0x1B)
#define INPUTCTRL_MUXPOS_PTAT    INPUTCTRL_MUXPOS(0x1C)
#define INPUTCTRL_MUXPOS_CTAT    INPUTCTRL_MUXPOS(0x1D)

#define INTFLAG_MASK  0x07
#define INTENCLR_MASK 0x07

#define SYNCBUSY_MASK 0x0FFF

#else

#define CTRLB_OFFSET     0x01
#define REFCTRL_OFFSET   0x02
#define INTENCLR_OFFSET  0x04
#define INTENSET_OFFSET  0x05
#define INTFLAG_OFFSET   0x06
#define INPUTCTRL_OFFSET 0x08
#define CTRLC_OFFSET     0x0A
#define AVGCTRL_OFFSET   0x0C
#define SAMPCTRL_OFFSET  0x0D
#define SWTRIG_OFFSET    0x18
#define SYNCBUSY_OFFSET  0x20
#define RESULT_OFFSET    0x24
#define CALIB_OFFSET     0x2C

#define DIFFMODE_OFFSET  CTRLC_OFFSET
#define RESSEL_OFFSET    CTRLC_OFFSET
#define PRESCALER_OFFSET CTRLA_OFFSET

#define DIFFMODE_MASK BIT(0)

#define PRESCALER_MASK GENMASK(10, 8)

#define REFCTRL_REFSEL_VDD_1_2 REFCTRL_REFSEL(2)
#define REFCTRL_REFSEL_AREFA   REFCTRL_REFSEL(3)
#define REFCTRL_REFSEL_VDD_1   REFCTRL_REFSEL(5)

#if defined(CONFIG_SOC_SERIES_SAML21) || defined(CONFIG_SOC_SERIES_SAMR34) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR35)
#define REFCTRL_REFSEL_AREFB REFCTRL_REFSEL(4)
#endif

#if defined(CONFIG_SOC_SERIES_SAML21) || defined(CONFIG_SOC_SERIES_SAMR34) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR35) ||                                                       \
	((defined(CONFIG_SOC_SERIES_SAMC20) || defined(CONFIG_SOC_SERIES_SAMC21)) &&               \
	 defined(CONFIG_SOC_SERIES_REVISION_N))
#define INPUTCTRL_MUXPOS_TEMP INPUTCTRL_MUXPOS(0x18)
#endif

#define INPUTCTRL_MUXPOS_BANDGAP INPUTCTRL_MUXPOS(0x19)

#define INTFLAG_MASK  0x07
#define INTENCLR_MASK 0x07

#define SYNCBUSY_MASK 0x07FF

#endif

#define CTRLA_ENABLE_BIT 1

#define INPUTCTRL_MUXNEG_MASK GENMASK(12, 8)
#define INPUTCTRL_MUXNEG(n)   FIELD_PREP(INPUTCTRL_MUXNEG_MASK, n)
#define INPUTCTRL_MUXNEG_GND  INPUTCTRL_MUXNEG(0x18)

#define INTENSET_RESRDY BIT(0)

#define REFCTRL_REFCOMP BIT(7)

#define RESSEL_MASK  GENMASK(5, 4)
#define RESSEL(n)    FIELD_PREP(RESSEL_MASK, n)
#define RESSEL_8BIT  RESSEL(3)
#define RESSEL_10BIT RESSEL(2)
#define RESSEL_12BIT RESSEL(0)
#define RESSEL_16BIT RESSEL(1)

#define PRESCALER(n) FIELD_PREP(PRESCALER_MASK, n)

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define PRESCALER_DIV4   PRESCALER(0)
#define PRESCALER_DIV8   PRESCALER(1)
#define PRESCALER_DIV16  PRESCALER(2)
#define PRESCALER_DIV32  PRESCALER(3)
#define PRESCALER_DIV64  PRESCALER(4)
#define PRESCALER_DIV128 PRESCALER(5)
#define PRESCALER_DIV256 PRESCALER(6)
#define PRESCALER_DIV512 PRESCALER(7)

#else

#define PRESCALER_DIV2   PRESCALER(0)
#define PRESCALER_DIV4   PRESCALER(1)
#define PRESCALER_DIV8   PRESCALER(2)
#define PRESCALER_DIV16  PRESCALER(3)
#define PRESCALER_DIV32  PRESCALER(4)
#define PRESCALER_DIV64  PRESCALER(5)
#define PRESCALER_DIV128 PRESCALER(6)
#define PRESCALER_DIV256 PRESCALER(7)

#endif

#define AVGCTRL_ADJRES_MASK    GENMASK(6, 4)
#define AVGCTRL_ADJRES(n)      FIELD_PREP(AVGCTRL_ADJRES_MASK, n)
#define AVGCTRL_SAMPLENUM_MASK GENMASK(3, 0)
#define AVGCTRL_SAMPLENUM(n)   FIELD_PREP(AVGCTRL_SAMPLENUM_MASK, n)

#define SAMPCTRL_SAMPLEN_MASK GENMASK(5, 0)
#define SAMPCTRL_SAMPLEN(n)   FIELD_PREP(SAMPCTRL_SAMPLEN_MASK, n)

#define SWTRIG_START BIT(1)

#if defined(CONFIG_SOC_SERIES_SAMC20) || defined(CONFIG_SOC_SERIES_SAMC21) ||                      \
	defined(CONFIG_SOC_SERIES_SAML21) || defined(CONFIG_SOC_SERIES_SAMR34) ||                  \
	defined(CONFIG_SOC_SERIES_SAMR35) || defined(CONFIG_SOC_SERIES_PIC32CMMC00)

#define ADC_SAM0_REFERENCE_ENABLE_PROTECTED
#endif

#define CALIB_BIASCOMP_MASK   GENMASK(2, 0)
#define CALIB_BIASR2R_MASK    GENMASK(6, 4)
#define CALIB_BIASREFBUF_MASK GENMASK(10, 8)

#define CALIB_BIAS_MASK        GENMASK(10, 8)
#define CALIB_LINEARITY_0_MASK GENMASK(4, 0)
#define CALIB_LINEARITY_1_MASK GENMASK(7, 5)

/* DSU chip revision access */

#define REG_DSU_DID_ADDR 0x41002018

#define DID_REVISION_MASK GENMASK(11, 8)

/* Bandgap control register */

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define REG_SYSCTRL_VREF_ADDR 0x40000840
#define VREF_TSEN_BIT         1
#define VREF_BGOUTEN_BIT      2

#define VREF_ADDR      REG_SYSCTRL_VREF_ADDR
#define VREF_BGREF_BIT VREF_BGOUTEN_BIT

#else

#if defined(CONFIG_SOC_SERIES_SAML21) || defined(CONFIG_SOC_SERIES_SAMR34) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR35)
#define REG_SUPC_VREF_ADDR 0x4000141C
#else
#define REG_SUPC_VREF_ADDR 0x4000181C
#endif

#define VREF_TSEN_BIT   1
#define VREF_VREFOE_BIT 2

#define VREF_ADDR      REG_SUPC_VREF_ADDR
#define VREF_BGREF_BIT VREF_VREFOE_BIT

#endif

/* NVMCTRL calibration register */

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define NVMCTRL_OTP4_ADDR 0x00806020
#define ADC_FUSES_ADDR    NVMCTRL_OTP4_ADDR

#define ADC0_LINEARITY_0_MASK GENMASK(31, 27)
#define ADC0_LINEARITY_1_MASK GENMASK(2, 0)
#define ADC0_BIAS_MASK        GENMASK(5, 3)

#else

#if defined(CONFIG_SOC_SERIES_SAMD51) || defined(CONFIG_SOC_SERIES_SAME51) ||                      \
	defined(CONFIG_SOC_SERIES_SAME53) || defined(CONFIG_SOC_SERIES_SAME54)

#define NVMCTRL_SW0_ADDR 0x00800080
#define ADC_FUSES_ADDR   NVMCTRL_SW0_ADDR

#define ADC0_BIASCOMP_MASK   GENMASK(4, 2)
#define ADC0_BIASREFBUF_MASK GENMASK(7, 5)
#define ADC0_BIASR2R_MASK    GENMASK(10, 8)

#define ADC1_BIASCOMP_MASK   GENMASK(18, 16)
#define ADC1_BIASREFBUF_MASK GENMASK(21, 19)
#define ADC1_BIASR2R_MASK    GENMASK(24, 22)

#else

#define NVMCTRL_OTP5_ADDR 0x00806020
#define ADC_FUSES_ADDR    NVMCTRL_OTP5_ADDR

#define ADC0_BIASCOMP_MASK   GENMASK(5, 3)
#define ADC0_BIASREFBUF_MASK GENMASK(2, 0)
#define ADC0_BIASR2R_MASK    0

#if defined(CONFIG_SOC_SERIES_SAMC21) || defined(CONFIG_SOC_SERIES_PIC32CMMC00)

#define ADC1_BIASCOMP_MASK   GENMASK(11, 9)
#define ADC1_BIASREFBUF_MASK GENMASK(8, 6)

#else

#define ADC1_BIASCOMP_MASK   0
#define ADC1_BIASREFBUF_MASK 0

#endif

#define ADC1_BIASR2R_MASK 0

#endif /* !(SOC_SERIES_SAMD51 || SOC_SERIES_SAME51 || SOC_SERIES_SAME53 || SOC_SERIES_SAME54) */

#endif /* !(SOC_SERIES_SAMD20 || SOC_SERIES_SAMD21 || SOC_SERIES_SAMR21) */

#define CALIB_MASK(name) UTIL_CAT(CALIB_, UTIL_CAT(name, _MASK))
#define ADC_MASK(idx, name)                                                                        \
	UTIL_CAT(AD, UTIL_CAT(C, UTIL_CAT(idx, UTIL_CAT(_, UTIL_CAT(name, _MASK)))))

#define GET_BIAS(idx, name, src) (ADC_MASK(idx, name) ? FIELD_GET(ADC_MASK(idx, name), src) : 0)
#define SET_BIAS(idx, name, src) FIELD_PREP(CALIB_MASK(name), GET_BIAS(idx, name, src))

#endif /* ZEPHYR_DRIVERS_PWM_PWM_SAM0_TC_H_ */
