/*
 * Copyright (c) 2025 GP Orcullo
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_COUNTER_COUNTER_SAM0_TC32_H_
#define ZEPHYR_DRIVERS_COUNTER_COUNTER_SAM0_TC32_H_

/* GCLK registers */

#define CLKCTRL_OFFSET 0x02
#define PCHCTRL_OFFSET 0x80

#define CLKCTRL_ID(n)  FIELD_PREP(GENMASK(5, 0), n)
#define CLKCTRL_GEN(n) FIELD_PREP(GENMASK(11, 8), n)
#define CLKCTRL_CLKEN  BIT(14)

#define PCHCTRL_GEN(n) FIELD_PREP(GENMASK(3, 0), n)
#define PCHCTRL_CHEN   BIT(6)

/* TC Registers */

#define CTRLA_OFFSET    0x00
#define CTRLBSET_OFFSET 0x05

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define READREQ_OFFSET  0x02
#define INTENCLR_OFFSET 0x0C
#define INTENSET_OFFSET 0x0D
#define INTFLAG_OFFSET  0x0E
#define STATUS_OFFSET   0x0F
#define COUNT_OFFSET    0x10
#define CC0_OFFSET      0x18
#define CC1_OFFSET      0x1C

#define CTRLA_WAVEGEN_MASK GENMASK(6, 5)
#define CTRLA_WAVEGEN(n)   FIELD_PREP(CTRLA_WAVEGEN_MASK, n)
#define CTRLA_WAVEGEN_MFRQ CTRLA_WAVEGEN(1)

#define READREQ_ADDR(n) FIELD_PREP(GENMASK(4, 0), n)
#define READREQ_RREQ    BIT(15)

#define CTRLBSET_CMD_MASK GENMASK(7, 6)

#define INTENCLR_MASK 0x3B

#define STATUS_SYNCBUSY BIT(7)

#else

#define INTENCLR_OFFSET 0x08
#define INTENSET_OFFSET 0x09
#define INTFLAG_OFFSET  0x0A
#define WAVE_OFFSET     0x0C
#define SYNCBUSY_OFFSET 0x10
#define COUNT_OFFSET    0x14
#define CC0_OFFSET      0x1C
#define CC1_OFFSET      0x20

#define CTRLA_WAVEGEN_MFRQ 0

#define CTRLBSET_CMD_MASK GENMASK(7, 5)

#define INTENCLR_MASK 0x33

#define WAVE_WAVEGEN(n)   FIELD_PREP(WAVE_WAVEGEN_MASK, n)
#define WAVE_WAVEGEN_MFRQ WAVE_WAVEGEN(1)

#define WAVE_WAVEGEN_MASK GENMASK(1, 0)

#define SYNCBUSY_MASK GENMASK(7, 0)

#endif

#define CTRLA_ENABLE_BIT   1
#define CTRLA_MODE_MASK    GENMASK(3, 2)
#define CTRLA_MODE(n)      FIELD_PREP(CTRLA_MODE_MASK, n)
#define CTRLA_PRESCALER(n) FIELD_PREP(GENMASK(10, 8), n)

#define CTRLA_MODE_COUNT32      CTRLA_MODE(2)
#define CTRLA_PRESCALER_DIV1    CTRLA_PRESCALER(0)
#define CTRLA_PRESCALER_DIV2    CTRLA_PRESCALER(1)
#define CTRLA_PRESCALER_DIV4    CTRLA_PRESCALER(2)
#define CTRLA_PRESCALER_DIV8    CTRLA_PRESCALER(3)
#define CTRLA_PRESCALER_DIV16   CTRLA_PRESCALER(4)
#define CTRLA_PRESCALER_DIV64   CTRLA_PRESCALER(5)
#define CTRLA_PRESCALER_DIV256  CTRLA_PRESCALER(6)
#define CTRLA_PRESCALER_DIV1024 CTRLA_PRESCALER(7)

#define CTRLBSET_CMD(n)        FIELD_PREP(CTRLBSET_CMD_MASK, n)
#define CTRLBSET_CMD_RETRIGGER CTRLBSET_CMD(1)
#define CTRLBSET_CMD_STOP      CTRLBSET_CMD(2)
#define CTRLBSET_CMD_READSYNC  CTRLBSET_CMD(4)

#define INTENCLR_MC0 BIT(4)
#define INTENCLR_MC1 BIT(5)

#define INTENSET_MC0 BIT(4)
#define INTENSET_MC1 BIT(5)

#define INTFLAG_MC0 BIT(4)
#define INTFLAG_MC1 BIT(5)

#endif /* ZEPHYR_DRIVERS_COUNTER_COUNTER_SAM0_TC32_H_ */
