/*
 * Copyright (c) 2025 GP Orcullo
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SERIAL_UART_SAM0_H_
#define ZEPHYR_DRIVERS_SERIAL_UART_SAM0_H_

#define GCLK_CLKCTRL_OFS 0x02
#define GCLK_PCHCTRL_OFS 0x80

#ifndef GCLK_PCHCTRL_CHEN
#define GCLK_PCHCTRL_GEN(n) FIELD_PREP(GENMASK(3, 0), n)
#define GCLK_PCHCTRL_CHEN   BIT(6)
#endif

#ifndef GCLK_CLKCTRL_CLKEN
#define GCLK_CLKCTRL_ID(n)  FIELD_PREP(GENMASK(5, 0), n)
#define GCLK_CLKCTRL_GEN(n) FIELD_PREP(GENMASK(11, 8), n)
#define GCLK_CLKCTRL_CLKEN  BIT(14)
#endif

#define USART_CTRLA_OFFSET 0x00
#define USART_CTRLB_OFFSET 0x04

#if defined(CONFIG_SOC_SERIES_SAMD20)

#define USART_BAUD_OFFSET     0x0A
#define USART_INTENCLR_OFFSET 0x0C
#define USART_INTENSET_OFFSET 0x0D
#define USART_INTFLAG_OFFSET  0x0E
#define USART_STATUS_OFFSET   0x10
#define USART_DATA_OFFSET     0x18

#define USART_INTENCLR_MASK 0x0F

#else

#define USART_BAUD_OFFSET     0x0C
#define USART_INTENCLR_OFFSET 0x14
#define USART_INTENSET_OFFSET 0x16
#define USART_INTFLAG_OFFSET  0x18
#define USART_STATUS_OFFSET   0x1A
#define USART_SYNCBUSY_OFFSET 0x1C
#define USART_DATA_OFFSET     0x28

#define USART_INTENCLR_MASK 0xBF

#endif

#define USART_CTRLA_ENABLE_BIT 1
#define USART_CTRLA_MODE(n)    FIELD_PREP(GENMASK(4, 2), n)
#define USART_CTRLA_SAMPR(n)   FIELD_PREP(GENMASK(15, 13), n)
#define USART_CTRLA_TXPO_BIT   16
#define USART_CTRLA_RXPO_BIT   20
#define USART_CTRLA_FORM_BIT   24
#define USART_CTRLA_FORM(n)    FIELD_PREP(GENMASK(27, 24), n)
#define USART_CTRLA_CPOL_BIT   29
#define USART_CTRLA_DORD_BIT   30

#define USART_CTRLB_CHSIZE_MASK GENMASK(2, 0)
#define USART_CTRLB_CHSIZE(n)   FIELD_PREP(USART_CTRLB_CHSIZE_MASK, n)
#define USART_CTRLB_SBMODE_BIT  6
#define USART_CTRLB_COLDEN_BIT  8
#define USART_CTRLB_PMODE_BIT   13
#define USART_CTRLB_TXEN        BIT(16)
#define USART_CTRLB_RXEN        BIT(17)

#define USART_INTFLAG_DRE   BIT(0)
#define USART_INTFLAG_TXC   BIT(1)
#define USART_INTFLAG_RXC   BIT(2)
#define USART_INTFLAG_RXS   BIT(3)
#define USART_INTFLAG_CTSIC BIT(4)
#define USART_INTFLAG_RXBRK BIT(5)
#define USART_INTFLAG_ERROR BIT(7)

#define USART_INTENSET_DRE   BIT(0)
#define USART_INTENSET_TXC   BIT(1)
#define USART_INTENSET_RXC   BIT(2)
#define USART_INTENSET_ERROR BIT(7)

#define USART_INTENCLR_DRE   BIT(0)
#define USART_INTENCLR_TXC   BIT(1)
#define USART_INTENCLR_RXC   BIT(2)
#define USART_INTENCLR_RXS   BIT(3)
#define USART_INTENCLR_CTSIC BIT(4)
#define USART_INTENCLR_RXBRK BIT(5)
#define USART_INTENCLR_ERROR BIT(7)

#define USART_STATUS_PERR_BIT     0
#define USART_STATUS_FERR_BIT     1
#define USART_STATUS_BUFOVF_BIT   2
#define USART_STATUS_ISF_BIT      4
#define USART_STATUS_COLL_BIT     5
#define USART_STATUS_SYNCBUSY_BIT 15

#if defined(CONFIG_SOC_SERIES_SAMD51) || defined(CONFIG_SOC_SERIES_SAME51) ||                      \
	defined(CONFIG_SOC_SERIES_SAME53) || defined(CONFIG_SOC_SERIES_SAME54)

#define USART_SYNCBUSY_MASK GENMASK(4, 0)
#else
#define USART_SYNCBUSY_MASK GENMASK(2, 0)
#endif

#endif /* ZEPHYR_DRIVERS_SERIAL_UART_SAM0_H_ */
