/*
 * Copyright (c) 2025 GP Orcullo
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_PWM_PWM_SAM0_TC_H_
#define ZEPHYR_DRIVERS_PWM_PWM_SAM0_TC_H_

/* GCLK registers */

#define CLKCTRL_OFFSET 0x02
#define PCHCTRL_OFFSET 0x80

#define CLKCTRL_ID(n)  FIELD_PREP(GENMASK(5, 0), n)
#define CLKCTRL_GEN(n) FIELD_PREP(GENMASK(11, 8), n)
#define CLKCTRL_CLKEN  BIT(14)

#define PCHCTRL_GEN(n) FIELD_PREP(GENMASK(3, 0), n)
#define PCHCTRL_CHEN   BIT(6)

/* TC Registers */

#define CTRLA_OFFSET 0x00

#if defined(CONFIG_SOC_SERIES_SAMD20) || defined(CONFIG_SOC_SERIES_SAMD21) ||                      \
	defined(CONFIG_SOC_SERIES_SAMR21)

#define CTRLC_OFFSET  0x06
#define STATUS_OFFSET 0x0F
#define PER_OFFSET    0x14
#define CC_OFFSET     0x18

#define WAVE_OFFSET CTRLA_OFFSET

#define CTRLA_PRESCSYNC_MASK GENMASK(13, 12)

#define DRVCTRL_OFFSET CTRLC_OFFSET

#define STATUS_SYNCBUSY BIT(7)

#define WAVE_WAVEGEN_MASK GENMASK(6, 5)

#else

#define STATUS_OFFSET   0x0B
#define WAVE_OFFSET     0x0C
#define DRVCTRL_OFFSET  0x0D
#define SYNCBUSY_OFFSET 0x10
#define PERBUF_OFFSET   0x2F
#define CCBUF_OFFSET    0x30

#define CTRLA_PRESCSYNC_MASK GENMASK(5, 4)

#define WAVE_WAVEGEN_MASK GENMASK(1, 0)

/* Use buffered version */

#define PER_OFFSET PERBUF_OFFSET
#define CC_OFFSET  CCBUF_OFFSET

#endif

#define CTRLA_SWRST_BIT    0
#define CTRLA_ENABLE_BIT   1
#define CTRLA_PRESCALER(n) FIELD_PREP(GENMASK(10, 8), n)
#define CTRLA_MODE_MASK    GENMASK(3, 2)
#define CTRLA_MODE(n)      FIELD_PREP(CTRLA_MODE_MASK, n)
#define CTRLA_MODE_COUNT8  CTRLA_MODE(1)
#define CTRLA_MODE_COUNT16 CTRLA_MODE(0)
#define CTRLA_PRESCSYNC(n) FIELD_PREP(CTRLA_PRESCSYNC_MASK, n)

#define CTRLA_PRESCSYNC_PRESC CTRLA_PRESCSYNC(1)

#define CTRLA_PRESCALER_DIV1    CTRLA_PRESCALER(0)
#define CTRLA_PRESCALER_DIV2    CTRLA_PRESCALER(1)
#define CTRLA_PRESCALER_DIV4    CTRLA_PRESCALER(2)
#define CTRLA_PRESCALER_DIV8    CTRLA_PRESCALER(3)
#define CTRLA_PRESCALER_DIV16   CTRLA_PRESCALER(4)
#define CTRLA_PRESCALER_DIV64   CTRLA_PRESCALER(5)
#define CTRLA_PRESCALER_DIV256  CTRLA_PRESCALER(6)
#define CTRLA_PRESCALER_DIV1024 CTRLA_PRESCALER(7)

#define WAVE_WAVEGEN(n)   FIELD_PREP(WAVE_WAVEGEN_MASK, n)
#define WAVE_WAVEGEN_NPWM WAVE_WAVEGEN(2)
#define WAVE_WAVEGEN_MPWM WAVE_WAVEGEN(3)

#define DRVCTRL_INVEN_MASK GENMASK(1, 0)

#endif /* ZEPHYR_DRIVERS_PWM_PWM_SAM0_TC_H_ */
