/*
 * Copyright (c) 2025 GP Orcullo
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_PWM_PWM_SAM0_TCC_H_
#define ZEPHYR_DRIVERS_PWM_PWM_SAM0_TCC_H_

/* GCLK registers */

#define CLKCTRL_OFFSET 0x02
#define PCHCTRL_OFFSET 0x80

#define CLKCTRL_ID(n)  FIELD_PREP(GENMASK(5, 0), n)
#define CLKCTRL_GEN(n) FIELD_PREP(GENMASK(11, 8), n)
#define CLKCTRL_CLKEN  BIT(14)

#define PCHCTRL_GEN(n) FIELD_PREP(GENMASK(3, 0), n)
#define PCHCTRL_CHEN   BIT(6)

/* TCC Registers */

#define CTRLA_OFFSET    0x00
#define SYNCBUSY_OFFSET 0x08
#define DRVCTRL_OFFSET  0x18
#define WAVE_OFFSET     0x3C
#define PER_OFFSET      0x40
#define PERBUF_OFFSET   0x6C
#define CCBUF_OFFSET    0x70

#define CTRLA_SWRST_BIT    0
#define CTRLA_ENABLE_BIT   1
#define CTRLA_PRESCALER(n) FIELD_PREP(GENMASK(10, 8), n)

#define CTRLA_PRESCALER_DIV1    CTRLA_PRESCALER(0)
#define CTRLA_PRESCALER_DIV2    CTRLA_PRESCALER(1)
#define CTRLA_PRESCALER_DIV4    CTRLA_PRESCALER(2)
#define CTRLA_PRESCALER_DIV8    CTRLA_PRESCALER(3)
#define CTRLA_PRESCALER_DIV16   CTRLA_PRESCALER(4)
#define CTRLA_PRESCALER_DIV64   CTRLA_PRESCALER(5)
#define CTRLA_PRESCALER_DIV256  CTRLA_PRESCALER(6)
#define CTRLA_PRESCALER_DIV1024 CTRLA_PRESCALER(7)

#define DRVCTRL_INVEN_MASK GENMASK(23, 16)

#define WAVE_WAVEGEN_MASK GENMASK(2, 0)
#define WAVE_WAVEGEN(n)   FIELD_PREP(WAVE_WAVEGEN_MASK, n)
#define WAVE_WAVEGEN_NPWM WAVE_WAVEGEN(2)

#define PER_PER(n) FIELD_PREP(GENMASK(24, 0), n)

#define PERBUF_PERBUF(n) FIELD_PREP(GENMASK(23, 0), n)

#define CCBUF_CCBUF(n) FIELD_PREP(GENMASK(23, 0), n)

#endif /* ZEPHYR_DRIVERS_PWM_PWM_SAM0_TCC_H_ */
